spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yobatis
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

mybatis:
  mapper-locations: classpath:mybatis-mappers/*.xml
logging:
  level:
    root: debug


