package org.yobatis.entity.criteria;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

// WARNING - @mbg.generated
// This file is automatically generated by MyBatis Generator, do not modify.
public class EmployeeCriteria extends BaseCriteria {
    private static final Set<String> COLUMNS;

    static {
        COLUMNS = new HashSet<>();
        COLUMNS.add("id");
        COLUMNS.add("name");
        COLUMNS.add("phone");
    }

    public EmployeeCriteria ascOrderBy(String  ... fields) {
        addOrderBy("asc", fields);
        return this;
    }

    public EmployeeCriteria descOrderBy(String  ... fields) {
        addOrderBy("desc", fields);
        return this;
    }

    public EmployeeCriteria or() {
        oredCriteria.add(new BracketCriteria());
        return this;
    }

    public EmployeeCriteria setLimit(Long limit) {
        this.limit = limit;
        return this;
    }

    public EmployeeCriteria setOffset(Long offset) {
        this.offset = offset;
        return this;
    }

    public EmployeeCriteria setForUpdate(boolean forUpdate) {
        this.forUpdate = forUpdate;
        return this;
    }

    @Override
    protected boolean hasColumn(String column) {
        return COLUMNS.contains(column);
    }

    public EmployeeCriteria andIdIsNull() {
        lastCriteria().addCriterion("id is null");
        return this;
    }

    public EmployeeCriteria andIdIsNotNull() {
        lastCriteria().addCriterion("id is not null");
        return this;
    }

    public EmployeeCriteria andIdEqualTo(Long value) {
        lastCriteria().addCriterion("id =", value, "id");
        return this;
    }

    public EmployeeCriteria andIdNotEqualTo(Long value) {
        lastCriteria().addCriterion("id <>", value, "id");
        return this;
    }

    public EmployeeCriteria andIdGreaterThan(Long value) {
        lastCriteria().addCriterion("id >", value, "id");
        return this;
    }

    public EmployeeCriteria andIdGreaterThanOrEqualTo(Long value) {
        lastCriteria().addCriterion("id >=", value, "id");
        return this;
    }

    public EmployeeCriteria andIdLessThan(Long value) {
        lastCriteria().addCriterion("id <", value, "id");
        return this;
    }

    public EmployeeCriteria andIdLessThanOrEqualTo(Long value) {
        lastCriteria().addCriterion("id <=", value, "id");
        return this;
    }

    public EmployeeCriteria andIdIn(List<Long> values) {
        lastCriteria().addCriterion("id in", values, "id");
        return this;
    }

    public EmployeeCriteria andIdNotIn(List<Long> values) {
        lastCriteria().addCriterion("id not in", values, "id");
        return this;
    }

    public EmployeeCriteria andIdBetween(Long value1, Long value2) {
        lastCriteria().addCriterion("id between", value1, value2, "id");
        return this;
    }

    public EmployeeCriteria andIdNotBetween(Long value1, Long value2) {
        lastCriteria().addCriterion("id not between", value1, value2, "id");
        return this;
    }

    public EmployeeCriteria andNameIsNull() {
        lastCriteria().addCriterion("name is null");
        return this;
    }

    public EmployeeCriteria andNameIsNotNull() {
        lastCriteria().addCriterion("name is not null");
        return this;
    }

    public EmployeeCriteria andNameEqualTo(String value) {
        lastCriteria().addCriterion("name =", value, "name");
        return this;
    }

    public EmployeeCriteria andNameNotEqualTo(String value) {
        lastCriteria().addCriterion("name <>", value, "name");
        return this;
    }

    public EmployeeCriteria andNameGreaterThan(String value) {
        lastCriteria().addCriterion("name >", value, "name");
        return this;
    }

    public EmployeeCriteria andNameGreaterThanOrEqualTo(String value) {
        lastCriteria().addCriterion("name >=", value, "name");
        return this;
    }

    public EmployeeCriteria andNameLessThan(String value) {
        lastCriteria().addCriterion("name <", value, "name");
        return this;
    }

    public EmployeeCriteria andNameLessThanOrEqualTo(String value) {
        lastCriteria().addCriterion("name <=", value, "name");
        return this;
    }

    public EmployeeCriteria andNameLike(String value) {
        lastCriteria().addCriterion("name like", value, "name");
        return this;
    }

    public EmployeeCriteria andNameNotLike(String value) {
        lastCriteria().addCriterion("name not like", value, "name");
        return this;
    }

    public EmployeeCriteria andNameIn(List<String> values) {
        lastCriteria().addCriterion("name in", values, "name");
        return this;
    }

    public EmployeeCriteria andNameNotIn(List<String> values) {
        lastCriteria().addCriterion("name not in", values, "name");
        return this;
    }

    public EmployeeCriteria andNameBetween(String value1, String value2) {
        lastCriteria().addCriterion("name between", value1, value2, "name");
        return this;
    }

    public EmployeeCriteria andNameNotBetween(String value1, String value2) {
        lastCriteria().addCriterion("name not between", value1, value2, "name");
        return this;
    }

    public EmployeeCriteria andPhoneIsNull() {
        lastCriteria().addCriterion("phone is null");
        return this;
    }

    public EmployeeCriteria andPhoneIsNotNull() {
        lastCriteria().addCriterion("phone is not null");
        return this;
    }

    public EmployeeCriteria andPhoneEqualTo(String value) {
        lastCriteria().addCriterion("phone =", value, "phone");
        return this;
    }

    public EmployeeCriteria andPhoneNotEqualTo(String value) {
        lastCriteria().addCriterion("phone <>", value, "phone");
        return this;
    }

    public EmployeeCriteria andPhoneGreaterThan(String value) {
        lastCriteria().addCriterion("phone >", value, "phone");
        return this;
    }

    public EmployeeCriteria andPhoneGreaterThanOrEqualTo(String value) {
        lastCriteria().addCriterion("phone >=", value, "phone");
        return this;
    }

    public EmployeeCriteria andPhoneLessThan(String value) {
        lastCriteria().addCriterion("phone <", value, "phone");
        return this;
    }

    public EmployeeCriteria andPhoneLessThanOrEqualTo(String value) {
        lastCriteria().addCriterion("phone <=", value, "phone");
        return this;
    }

    public EmployeeCriteria andPhoneLike(String value) {
        lastCriteria().addCriterion("phone like", value, "phone");
        return this;
    }

    public EmployeeCriteria andPhoneNotLike(String value) {
        lastCriteria().addCriterion("phone not like", value, "phone");
        return this;
    }

    public EmployeeCriteria andPhoneIn(List<String> values) {
        lastCriteria().addCriterion("phone in", values, "phone");
        return this;
    }

    public EmployeeCriteria andPhoneNotIn(List<String> values) {
        lastCriteria().addCriterion("phone not in", values, "phone");
        return this;
    }

    public EmployeeCriteria andPhoneBetween(String value1, String value2) {
        lastCriteria().addCriterion("phone between", value1, value2, "phone");
        return this;
    }

    public EmployeeCriteria andPhoneNotBetween(String value1, String value2) {
        lastCriteria().addCriterion("phone not between", value1, value2, "phone");
        return this;
    }

    public static EmployeeCriteria idIsNull() {
        return new EmployeeCriteria().andIdIsNull();
    }

    public static EmployeeCriteria idIsNotNull() {
        return new EmployeeCriteria().andIdIsNotNull();
    }

    public static EmployeeCriteria idEqualTo(Long value) {
        return new EmployeeCriteria().andIdEqualTo(value);
    }

    public static EmployeeCriteria idNotEqualTo(Long value) {
        return new EmployeeCriteria().andIdNotEqualTo(value);
    }

    public static EmployeeCriteria idGreaterThan(Long value) {
        return new EmployeeCriteria().andIdGreaterThan(value);
    }

    public static EmployeeCriteria idGreaterThanOrEqualTo(Long value) {
        return new EmployeeCriteria().andIdGreaterThanOrEqualTo(value);
    }

    public static EmployeeCriteria idLessThan(Long value) {
        return new EmployeeCriteria().andIdLessThan(value);
    }

    public static EmployeeCriteria idLessThanOrEqualTo(Long value) {
        return new EmployeeCriteria().andIdLessThanOrEqualTo(value);
    }

    public static EmployeeCriteria idIn(List<Long> values) {
        return new EmployeeCriteria().andIdIn(values);
    }

    public static EmployeeCriteria idNotIn(List<Long> values) {
        return new EmployeeCriteria().andIdNotIn(values);
    }

    public static EmployeeCriteria idBetween(Long value1, Long value2) {
        return new EmployeeCriteria().andIdBetween(value1, value2);
    }

    public static EmployeeCriteria idNotBetween(Long value1, Long value2) {
        return new EmployeeCriteria().andIdNotBetween(value1, value2);
    }

    public static EmployeeCriteria nameIsNull() {
        return new EmployeeCriteria().andNameIsNull();
    }

    public static EmployeeCriteria nameIsNotNull() {
        return new EmployeeCriteria().andNameIsNotNull();
    }

    public static EmployeeCriteria nameEqualTo(String value) {
        return new EmployeeCriteria().andNameEqualTo(value);
    }

    public static EmployeeCriteria nameNotEqualTo(String value) {
        return new EmployeeCriteria().andNameNotEqualTo(value);
    }

    public static EmployeeCriteria nameGreaterThan(String value) {
        return new EmployeeCriteria().andNameGreaterThan(value);
    }

    public static EmployeeCriteria nameGreaterThanOrEqualTo(String value) {
        return new EmployeeCriteria().andNameGreaterThanOrEqualTo(value);
    }

    public static EmployeeCriteria nameLessThan(String value) {
        return new EmployeeCriteria().andNameLessThan(value);
    }

    public static EmployeeCriteria nameLessThanOrEqualTo(String value) {
        return new EmployeeCriteria().andNameLessThanOrEqualTo(value);
    }

    public static EmployeeCriteria nameLike(String value) {
        return new EmployeeCriteria().andNameLike(value);
    }

    public static EmployeeCriteria nameNotLike(String value) {
        return new EmployeeCriteria().andNameNotLike(value);
    }

    public static EmployeeCriteria nameIn(List<String> values) {
        return new EmployeeCriteria().andNameIn(values);
    }

    public static EmployeeCriteria nameNotIn(List<String> values) {
        return new EmployeeCriteria().andNameNotIn(values);
    }

    public static EmployeeCriteria nameBetween(String value1, String value2) {
        return new EmployeeCriteria().andNameBetween(value1, value2);
    }

    public static EmployeeCriteria nameNotBetween(String value1, String value2) {
        return new EmployeeCriteria().andNameNotBetween(value1, value2);
    }

    public static EmployeeCriteria phoneIsNull() {
        return new EmployeeCriteria().andPhoneIsNull();
    }

    public static EmployeeCriteria phoneIsNotNull() {
        return new EmployeeCriteria().andPhoneIsNotNull();
    }

    public static EmployeeCriteria phoneEqualTo(String value) {
        return new EmployeeCriteria().andPhoneEqualTo(value);
    }

    public static EmployeeCriteria phoneNotEqualTo(String value) {
        return new EmployeeCriteria().andPhoneNotEqualTo(value);
    }

    public static EmployeeCriteria phoneGreaterThan(String value) {
        return new EmployeeCriteria().andPhoneGreaterThan(value);
    }

    public static EmployeeCriteria phoneGreaterThanOrEqualTo(String value) {
        return new EmployeeCriteria().andPhoneGreaterThanOrEqualTo(value);
    }

    public static EmployeeCriteria phoneLessThan(String value) {
        return new EmployeeCriteria().andPhoneLessThan(value);
    }

    public static EmployeeCriteria phoneLessThanOrEqualTo(String value) {
        return new EmployeeCriteria().andPhoneLessThanOrEqualTo(value);
    }

    public static EmployeeCriteria phoneLike(String value) {
        return new EmployeeCriteria().andPhoneLike(value);
    }

    public static EmployeeCriteria phoneNotLike(String value) {
        return new EmployeeCriteria().andPhoneNotLike(value);
    }

    public static EmployeeCriteria phoneIn(List<String> values) {
        return new EmployeeCriteria().andPhoneIn(values);
    }

    public static EmployeeCriteria phoneNotIn(List<String> values) {
        return new EmployeeCriteria().andPhoneNotIn(values);
    }

    public static EmployeeCriteria phoneBetween(String value1, String value2) {
        return new EmployeeCriteria().andPhoneBetween(value1, value2);
    }

    public static EmployeeCriteria phoneNotBetween(String value1, String value2) {
        return new EmployeeCriteria().andPhoneNotBetween(value1, value2);
    }
}